### ISSUE TITLE
1.0.3 Version 4

### ISSUE THREAD

**Issue by franco27** [Akylas/com.akylas.documentscanner#10]
There is a problem, we cannot download this version.

On the Github application, the APK file is available, but when we click on it, there is an error message and it redirects to a Github page (file is missing).

And when using the internet browser, there are only source files.

**Comment by farfromrefug** [comment]
@franco27 thanks for pointing this out! something went wrong with the release. Will fix that tomorrow
Sorry

**Comment by farfromrefug** [comment]
@franco27 the release is fixed! thanks for reporting it
