### ISSUE TITLE
Won't Export PDF

### ISSUE THREAD

**Issue by rjm831** [Akylas/com.akylas.documentscanner#12]
Getting an error toast THIS CANVAS SCALE IS NOT A FUNCTION, then app simply gets stuck in a loop attempting to export.  I'm running a stock Samsung Galaxy Tab A7 tablet with Android 12.  Perhaps this issue has something to do with Samsung's photo editor messing things up?  Using v1-1-2-7

**Comment by farfromrefug** [comment]
@rjm831 never heard of this one. will try to figure it out

**Comment by rjm831** [comment]
Thanks.  With no root access I dont know if I can help with logs, but anything else be happy to help.  Great app and appreciate the work you're doing.  Hope I can get it to work on my tablet.

**Comment by Ox3rror** [comment]
I got the same error as well while exporting pdf. Device : OnePlus 11, Android 14 Application version : v1.1.2 Build 7

**Comment by farfromrefug** [comment]
@Ox3rror @rjm831 can one of you take a screenshot of the error ?

**Comment by Ox3rror** [comment]
> @Ox3rror @rjm831 can one of you take a screenshot of the error ?

![Screenshot_2023-12-16-02-49-37-10_95dcfb87bea3b5fbac634956b75eabe9](https://github.com/Akylas/com.akylas.documentscanner/assets/132026922/30bf9153-8eb7-4224-8ab9-fac75f9b5630)

**Comment by shompoe** [comment]
I get exactly the same error. Pixel 4a GrapheneOS

**Comment by farfromrefug** [comment]
thanks I'll try to reproduce

**Comment by shompoe** [comment]
Maybe worth mentioning that I can open and view pdf, I just cannot export it. Also, the filename prompt appears but this error occurs after accepting the filename.

**Comment by farfromrefug** [comment]
@shompoe @rjm831 could you please install [this](http://gofile.me/4pKGL/5dacOArni) build and reproduce the bug? That build has sentry enabled (personal hosted sentry instance). 
Once you get the error dialog, please kill and re open the app to ensure the bug report is sent.
That way i can clearly see (logs, callstack) what is happening.
Thanks!

**Comment by shompoe** [comment]
I just downloaded that build and it worked, for the first time I was able to save a pdf.

---
Mark Desrousseaux



16 Dec 2023, 18:02 by ***@***.***:

**Comment by farfromrefug** [comment]
@shompoe OK the issue is that it is a debug build. does it still not work with latest release I made today on github ?

**Comment by methicodx** [comment]
last built 1.1.3.8 still have bug 

i wasnt export pdf 

![Screenshot_20231216_204826_OSS Document Scanner.jpg](https://github.com/Akylas/com.akylas.documentscanner/assets/141909414/46210ed8-cbbf-43aa-93a7-ddd164f08f87)

![Screenshot_20231216_204727_OSS Document Scanner.jpg](https://github.com/Akylas/com.akylas.documentscanner/assets/141909414/0e100af5-98ac-4bda-a121-619735b13e81)

**Comment by shompoe** [comment]
No, latest release on GitHub does not work.

---
Mark Desrousseaux



16 Dec 2023, 19:21 by ***@***.***:

**Comment by farfromrefug** [comment]
@shompoe @rjm831 @Ox3rror @methicodx  Just released a new version with the fix.
Sorry for the issue and the time it took me to fix this

**Comment by Ox3rror** [comment]
the new version fixed the issue, Thanks dev.

**Comment by rjm831** [comment]
Verified build 9 fixed the problem.  Great work, and thanks to all of you!

**Comment by methicodx** [comment]
all good

**Comment by NA0341** [comment]
Does the "Open" function work for you guys?
On my device (Samsung S8 SM-G950F, Android 9) it the export function works - but when using the "Open" - button, the receiving PDF - Reader (Librera PRO) spills an error (opening the saved pdf with it works fine).

If the intent is sent with AppManager's Interceptor, there's another message before the error: "Activity result: (nul)"

Below's a screenshot of the error message as well as the intent sent by your application in AppManagers Interceptor.

Does anyone else have issues using the open function?
(I'm not sure since this might very well be an issue on my device.)


![Screenshot_20231217-135433](https://github.com/Akylas/com.akylas.documentscanner/assets/26059513/849d9cbb-770a-4143-966f-0e6090efcbcc)
![Screenshot_20231217-135403_App Manager](https://github.com/Akylas/com.akylas.documentscanner/assets/26059513/62ad174c-501f-4f68-b046-a1e544d9a067)

**Comment by farfromrefug** [comment]
@NA0341 thanks for the detailed explanation. will try to reproduce

**Comment by NA0341** [comment]
@farfromrefug I think this is fixed. I couldn't reproduce the errors with v. 1.2.25 Build 35.

**Comment by rjm831** [comment]
Export is working fine for me with latest build, & everything else seems to function too.  Thanks dev!  Issue closed (for me, anyway).
