### ISSUE TITLE
[Feature Request] Auto crop 

### ISSUE THREAD

**Issue by Subhashis2007** [Akylas/com.akylas.documentscanner#13]
This project is amazing, most of the other OSS scanners just left after 1-2 updates, but man you're amazing.

I'd like to request a feature, using which each photo we click can be cropped automatically if possible. As seen in several proprietary softwares like camscanner, and xyz

**Comment by Sureshgorai25** [comment]
+ a button to revert crop will also useful, bcz if sometimes it doesn't crop perfectly then we can switch to full image easily.
Thanks

**Comment by Subhashis2007** [comment]
oh right something like, getting an overview before converting the document..

**Comment by Sureshgorai25** [comment]
Yep

**Comment by farfromrefug** [comment]
@Subhashis2007 I dont understand. the app already detect the document and auto crop it.

**Comment by Subhashis2007** [comment]
I see, it is there, but a little optimisation would be good,

**Comment by farfromrefug** [comment]
@Subhashis2007 what do you mean ?

**Comment by Subhashis2007** [comment]
Like if the viewfinder could be a little small, so that it would be easier to o navigate
