### ISSUE TITLE
[Feature Requst] Batch scan

### ISSUE THREAD

**Issue by Subhashis2007** [Akylas/com.akylas.documentscanner#14]
Another feature which will makes lives easier is to add an option in which we can scan images in batches of them, and when we convert them into PDF it will be a single document or different scanned files.

Thanks a lot for your work.
Hope so this project touches new heights of success :)

**Comment by farfromrefug** [comment]
@Subhashis2007 it is already there in the camera screen. there is a button for that (might not be evident to see the meaning)
