### ISSUE TITLE
[FR] Viewfinder is too big

### ISSUE THREAD

**Issue by Sureshgorai25** [Akylas/com.akylas.documentscanner#15]
The viewfinder is very big, it's very hard to capture a document. I meant changing the aspect ratio of it (i.e making it small) will be very good. See CamScanner's and DocScanner's viewfinder for example 
• Auto capture is very useful for capturing docs in batches
Thanks

**Comment by Sureshgorai25** [comment]
![Screenshot_20231216-132945](https://github.com/Akylas/com.akylas.documentscanner/assets/93507842/f39ec5fe-7fb0-440d-b40b-0211ef716391)
![Screenshot_20231216-133025](https://github.com/Akylas/com.akylas.documentscanner/assets/93507842/af3936e9-b70c-4a1a-9648-e2e86948363b)

Compare these ss, both at exact same height

**Comment by farfromrefug** [comment]
@Sureshgorai25 i need you to clarify when you say the viewfinder is too big. What is the issue? Are you not seeing the full picture of what the camera would take?
If i understand correctly you are saying seeing the ratio of the full screen camera view you are missing part of the actual capture image on the left and the right (shown in preview). And thus you dont see the full document even though in capture it would be completely in "range" of the captured image.
Is that what you mean?

**Comment by Subhashis2007** [comment]
I think he meant that the camera opens in full screen always, and it is hard to get the page-to-be-scanned fit into the camera, if the camera interface would be a little bit smaller it would be more convenient.
![Untitled](https://github.com/Akylas/com.akylas.documentscanner/assets/113865986/38b91cca-c72f-45be-9292-a0f97035cd3a)

Or you just can add this feature

**Comment by Sureshgorai25** [comment]
Yes, this is what I meant
Thanks @Subhashis2007

**Comment by farfromrefug** [comment]
@Sureshgorai25 @Subhashis2007 the newest version has a new camera layout

**Comment by Subhashis2007** [comment]
> @Sureshgorai25 @Subhashis2007 the newest version has a new camera layout

![photo_2023-12-20_07-23-56](https://github.com/Akylas/com.akylas.documentscanner/assets/113865986/e46671b8-ae08-400e-b7ce-e84cf9d8666e)

Nice this layout is a lot better. And makes things easier.

![photo_2023-12-20_07-23-52](https://github.com/Akylas/com.akylas.documentscanner/assets/113865986/f4757cd4-0a8d-4eac-a2c6-6401fb139b3c)

But still this layout feels more appealing.
And may be you can work on adding 4:3 ratio?

**Comment by Subhashis2007** [comment]
> @Sureshgorai25 @Subhashis2007 the newest version has a new camera layout

New layout is fairly good. But it is more appealing if there is also black borders on the top edge of the screen. And may be can you add a 4:3 mode?

**Comment by farfromrefug** [comment]
i  working on it. it needs a full rewrite

**Comment by Subhashis2007** [comment]
good luck

**Comment by Subhashis2007** [comment]
> i working on it. it needs a full rewrite

Great work on the latest 1.2.5.15
