### ISSUE TITLE
Black and white threshold

### ISSUE THREAD

**Issue by FattyNess** [Akylas/com.akylas.documentscanner#18]
Can you please add a slider to control threshold of the black and white filter. Some scans I take are from old books and so the paper there is more brown which is close to text color, so what I get is black text on black background.

**Comment by farfromrefug** [comment]
@FattyNess yes it is planned will try to add it soon. will be a long press on the black and white "item"

**Comment by FattyNess** [comment]
thanks a lot!

**Comment by farfromrefug** [comment]
@FattyNess it is in the latest version

**Comment by FattyNess** [comment]
I see, great job!
