### ISSUE TITLE
Bug: Impossible to take a picture from app.

### ISSUE THREAD

**Issue by Breizhux** [Akylas/com.akylas.documentscanner#2]
Hello,

Your application works like a charm... Except when I want to scan by taking a photo directly.
Here's how I do it:
 - I open the application (I give it the rights for the camera if necessary).
 - I take a sheet of paper and place it on a background of a different color.
 - I press the icon at the very bottom right to take a photo.
 - The application detects the edges of my sheet in real time.
 - But when I press the button to take the photo, the application seems to take the photo. Then, after a second, it displays the following error: "_java.lang.Exception: OpenCV(4.8.0) /home/ci/opencv/modules/core/src/matrix.cpp:424:error: (-215:Assertion failed) total() == 0 || data != NULL in function 'Mat'_".

On the other hand, I can load a photo from my local storage space, and there no problem.

Here's my hardware configuration:
 - Device: Xiaomi Mi A1
 - System: Android 13 (20-20231129-NIGHTLY-tissot)
 - Application installed from Fdroid, IssyOnDroid repository (https://apt.izzysoft.de/fdroid/index/apk/com.akylas.documentscanner)

Thanks in advance for anything you can do ;)

**Comment by farfromrefug** [comment]
@Breizhux thanks a lot for the report. will try to reproduce. might be something related to your xiaomi phone and the way get access to your photo. will hopefully have a new version out soon

**Comment by Breizhux** [comment]
Thanks for the feedback, I've done other tests.

On the Xiaomi Mi A2: no problem.
On another Xiaomi Mi A1, Android 10 /e/ system: exactly the same problem...

So it seems to be down to the model of smartphone. However, the other scanning apps didn't have this bug...
Perhaps there's some other information I can provide?

**Comment by farfromrefug** [comment]
@Breizhux great this can actually help me. Does it work with this app ? https://github.com/GrapheneOS/Camera
And so to be clear it crashes on 2 Mi a1, one on android 10 and one on android 13?

**Comment by Breizhux** [comment]
Ok.
I have installed the Camera application from GrapheneOS :
 - I still can't scan documents with your app. I get the same error message...
 - As for the GrapheneOS Camera application, I can take photos with it without any problem.

Yes, I can confirm that it crashes on the 2 Xiaomi Mi A1s running Android, one in version 10 and the other in version 13.

**Comment by esodigoyo** [comment]
Crashes on Moto G13 as well

**Comment by farfromrefug** [comment]
@Breizhux @esodigoyo thank you both for the report. I have reproduced and fixed it. New release coming hopefully today

**Comment by esodigoyo** [comment]
Last update already fixed it for me. Thank you!
