### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [Akylas/com.akylas.documentscanner#20]
Add material themed icon becoz it ruins my home screen

**Comment by farfromrefug** [comment]
You can use a launcher to change the icon. Or you can propose a new one ;)

**Comment by xmha97** [comment]
Please add the monochrome icon (like other apps):

![Screenshot_2023-12-19-00-01-37-678_de mm20 launcher2 release](https://github.com/Akylas/com.akylas.documentscanner/assets/23485114/7d1d4688-2ad7-422d-a96f-41cca28f7da6)

**Comment by farfromrefug** [comment]
It will be there soon. Now i am not a designer and i dont really like my icon. So if one of you is good with design and want to propose a new icon, dont hesitate!

**Comment by farfromrefug** [comment]
@xmha97 @saltsoftdrink the new version has a monochrome icon

**Comment by SpiritOTHawk** [comment]
![Screenshot_20240712-110236](https://github.com/user-attachments/assets/0482dc6b-0467-4c50-8e6a-6194fa423b0e)
