### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by FabulousOne** [Akylas/com.akylas.documentscanner#22]
Hi @farfromrefug 
Great to see another awesome app from you, after OSS weather and AlpiMaps.
I'd like to translate it in German, using weblate or transifex. Would that be possible? 
Cheers!

**Comment by farfromrefug** [comment]
Hey @FabulousOne. Thanks for the kind words!
I set up a project on weblate https://hosted.weblate.org/projects/oss-document-scanner/

**Comment by FabulousOne** [comment]
@farfromrefug ok, that looks good. Could you add German, so that I can translate into German, please?

**Comment by farfromrefug** [comment]
sure will do. thought you could add new ones

**Comment by farfromrefug** [comment]
@FabulousOne here you go https://hosted.weblate.org/projects/oss-document-scanner/application-strings/de/

**Comment by FabulousOne** [comment]
Thank you @farfromrefug , for opening the German translation.
But I noted that every translation is put into the "Glossar", which is a kind of vocabulary which is used for translating the strings. In other projects, I see the strings to translate, and a glossary where you can define the translation in order to be unified throughout the project.

You should perhaps check the settings, so that the glossary and the strings to be translated are separated. 

Merci beaucoup, c'est un projet enthousiasmant !

Fab
![hostedweblate](https://github.com/Akylas/com.akylas.documentscanner/assets/99396952/51bb84fc-d513-4aac-8b69-4fdce9ee28e8)

**Comment by farfromrefug** [comment]
@FabulousOne thanks for the feedback. i am new to weblate.  So now ApplicationStrings is not the glossary anymore.
Do i need to create another "glossary" component?

**Comment by jspast** [comment]
Hi @farfromrefug !
Thank you for this amazing app.
I would like to translate it to Brazilian Portuguese, though I couldn't find a way to add new languages on Weblate. Could you add Brazilian Portuguese or maybe change the settings so that anyone can add new languages? I am also new to Weblate so I am not sure how this works.

**Comment by farfromrefug** [comment]
@jspast thanks for the kind words! You should now be able to create a new language. Let me know if it works otherwise i ll do it myself

**Comment by jspast** [comment]
Thank you @farfromrefug !
Working as intended
