### ISSUE TITLE
Filters on scanned document not getting exported.

### ISSUE THREAD

**Issue by ashjas** [Akylas/com.akylas.documentscanner#23]
Steps:
- scan a new document
- apply BW or any other filter like invert (notice the preview applies the filter)
- hit share icon, and save.
- the output image does not contain the filters applied.

The enhancements like Enhance/whitepaper/color when saved through share icon are applied correctly to the output image.

I only need to save the output with filters applied, which does not work.

Thanks for this app..

**Comment by farfromrefug** [comment]
@ashjas good catch indeed i forgot to apply filters to exported image ! only applied to pdf.
Will fix ASAP!
