### ISSUE TITLE
is Multiselect images from gallery planned? 

### ISSUE THREAD

**Issue by ashjas** [Akylas/com.akylas.documentscanner#24]
It would be awsome to have the app process multiple images from the gallery atleast.
I cant seem to multi select more than one images in one go.
This will help in keeping related document pages in a single pdf.

Regards.

**Comment by farfromrefug** [comment]
@ashjas it is doable it is more a question of UX. If you select multiple i cant present you with the crop screen as it would be only one image.  I could add it but then it would automatically create a document (or add pages) with the found crop (or the default one).
Would that be good enough?

**Comment by ashjas** [comment]
Automatically would be fine, but manual override for a particular image would be required to fine time auto crop for that page.
--  Sent from my p≡p for Android.

**Comment by farfromrefug** [comment]
you could still recrop afterward on a per page basis.
will think if I can do something better
