### ISSUE TITLE
Blank screen after splash screen

### ISSUE THREAD

**Issue by billie80** [Akylas/com.akylas.documentscanner#29]
With the recent updates starting from version 1.2.5.13 the App doesn't work for me anymore. After the splash screen the screen turns blank and nothing happens. Even if I clear the App data. In this case after the spash screen storage permission is requested and then the screen turns blank. Version 1.2.5.12 is the last one that works.

This is on a device running Android 10.

**Comment by farfromrefug** [comment]
@billie80 really sorry about that. will fix it as soon as possible

**Comment by farfromrefug** [comment]
@billie80 trying to figure out what your issue could be. can you give me details :
* phone model
* phone language

**Comment by billie80** [comment]
I am using a Shift6mq (https://shop.shiftphones.com/shift6mq.html) which is not really a mainstream model. But I guess this is not relevant here because your second question might be spot on.
Language is set to German but as soon as I set it to English everything works again as expected.

**Comment by billie80** [comment]
German translation was added in between this versions. So maybe this is causing the issue.

**Comment by farfromrefug** [comment]
@billie80 awesome that must be it! Will fix

**Comment by billie80** [comment]
Just to let you know. I tested 1.2.5.16. Now I get further but when accessing the (display) settings the App crashes. Also I can not capture an image. When trying to capture it there is a crash as well.
This time however it also happens when I change the language to English.
No pressure though. Enjoy the festive season. Such things are not that important.
Happy Holidays!

**Comment by farfromrefug** [comment]
@billie80 very nice of you to say that. Though i dont like bugs :D 
I created a test release. Hopefully i will get bug reports on my sentry instance
https://github.com/Akylas/com.akylas.documentscanner/releases/tag/test_android

**Comment by billie80** [comment]
I downloaded the test release and now there are no crashes when entering the settings. 👍
Is it intended that the image is only captured if there is the green live document scanning preview? Before an image was captured anyway to allow extracting text.

**Comment by farfromrefug** [comment]
@billie80 not sure I get your new issue. 
you are talking about:
* opening the camera
* capturing a photo while no live document is detected

is that where the issue happens? indeed even with no live document detected a document taking approximately the whole picture should be recognized

**Comment by billie80** [comment]
It is when trying to capture an image.
It is almost impossible to get the live document and the image is only captured if there is a live document. Without, no full screen image is taken as you wrote. This is why I am asking. It used to be like this but not with the newer versions.
Can provide a screencast if it is helpful.

**Comment by farfromrefug** [comment]
@billie80 found your first crash too. Last version just released should hopefully fix it all for you.
Sorry for the trouble

**Comment by billie80** [comment]
I think we are getting there. 😃
However now I get a crash when trying to save the captured image. Happens independenly if I crop manually before or not.
Btw, is it okay to continue here? Probably it is better to open a new issues.

**Comment by farfromrefug** [comment]
@billie80 no problem if you continue there.  What do you mean by "save the capture image" ? trying to reproduce it

**Comment by billie80** [comment]
Actually it is not saving the image. After capturing there is the option to crop the image or confirm the capture. When confirming the App crashes.

**Comment by farfromrefug** [comment]
@billie80 should be fixed in latest version. hopefully everything works for you now

**Comment by billie80** [comment]
Thank you very much. Looks good now!
