### ISSUE TITLE
Cannot download Tesseract data

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [Akylas/com.akylas.documentscanner#35]
I always get a timeout error message, when I want to download the tesseract ocr data:

`java.net.SocketTimeoutException: failed to connect to github.com/... from ... after 100000ms`

I disabled all adblock things on the phone and my network.

Does someone outthere also have this issue?

**Comment by farfromrefug** [comment]
@klawdhfzasjhaa what language are you trying to download? Just tried again with english and it worked fine.

Can you manually download files from there https://github.com/tesseract-ocr/tessdata_best/raw/4.0.0/ ? on your phone? if not maybe on a computer?

**Comment by klawdhfzasjhaa** [comment]
The direct download worked (German, English). Now (1.2.7.17) it also worked in the app again.
Thanks for your help.
