### ISSUE TITLE
App crashed after clicking photo 

### ISSUE THREAD

**Issue by Zaxx69** [Akylas/com.akylas.documentscanner#40]
After i clicked a photo and pressed on the tick button ,the app crashed

Realme 8
Android 13
Latest version of ODS

I have got the logs ,idk if i should share it here

**Comment by farfromrefug** [comment]
@Zaxx69 thanks a lot for the report. Fixed. Will be released soon

**Comment by farfromrefug** [comment]
@Zaxx69 should be fixed in latest version

**Comment by Zaxx69** [comment]
Thank you
