### ISSUE TITLE
App crashes (stuck) on export to PDF

### ISSUE THREAD

**Issue by ryeger** [Akylas/com.akylas.documentscanner#44]
Description in the title.

**Comment by farfromrefug** [comment]
@ryeger did you change the export p
folder or is it still set to downloads?

**Comment by farfromrefug** [comment]
@ryeger i cant reproduce your issue. Please give more details:
* platform / device version
* how to reproduce

**Comment by billie80** [comment]
I have the same problem.
The App hangs when trying to export to PDF. It creates a zero byte file in the download folder. Exporting spins forever.
Happens in any case. Meaning it doesn't matter if the open, export, or preview route is taken. Also if the OCR overlay is drawn or not.
BTW. I don't see red option to change the export location.
Android 10 / Shift6mq

**Comment by ryeger** [comment]
Android 14, pixel 5.
I changed to another folder other than Downloads and still the same endless spinning of 'export'.
Also tried on android 13 in another device, same issue

**Comment by farfromrefug** [comment]
@ryeger @billie80 i fixed the bug. new version coming soon

**Comment by billie80** [comment]
Just tested it in the new version and exporting to PDF now works as expected. Thank you very much.

**Comment by S-Joao-V** [comment]
Tried exporting a set of images (15) captured with a prev version while running v1.2.11 Build 21, and got stuck in exporting, with android pop up to close the app due to no response. After some 30s the pdf was exported 13MB, so some feedback and handling of the wait is needed.

A new picture taken could be exported to pdf right away.

**Comment by farfromrefug** [comment]
@S-Joao-V not sure i understand. When you say `prev version` what do you mean?  you tried with latest 1.2.11 build 21 right? I will run some tests maybe it is the compress of the pdf which takes a long time. Could run that in a thread

**Comment by S-Joao-V** [comment]
@farfromrefug  the prev. version part of the comment can be ignored.
I've cleaned cache/data and captured a new document with 1.2.11 build 21, 30 pages / 17MB when exported.

While the "Exporting" message shows: App is not responding pop-up after some 30s, select wait, pop-up returns
After the "Document saved to <location>": App is not responding pop-up continues to return every 15s, select wait, repeat (even if app is not in the foreground anymore)

**Comment by farfromrefug** [comment]
@S-Joao-V ok i get it now. I just implemented threaded export, so should remove the not responding error
