### ISSUE TITLE
Language selector not working

### ISSUE THREAD

**Issue by stxm** [Akylas/com.akylas.documentscanner#45]
Lamguage selector shows all available languages but after tapping on a language the popout closes and the language remains English

Android 14

**Comment by farfromrefug** [comment]
@stxm should be fixed in latest. thanks for the report

**Comment by billie80** [comment]
I think it worked with 1.2.9.19 but now with 1.2.10.20 switching the language stopped working again.

**Comment by farfromrefug** [comment]
@billie80 you are right... this is an issue with my node_modules which gets broken every time I run yarn. have to fix it for good this time !

**Comment by billie80** [comment]
Now it works again. 👍
