### ISSUE TITLE
black UI text in dark mode

### ISSUE THREAD

**Issue by magmaus3** [Akylas/com.akylas.documentscanner#5]
In dark theme, text in some menus (like the theme switcher or the enhancement menu) uses black text instead of white, which makes it hard or even impossible to read.

![Screenshot of the theme switcher menu with dark theme](https://github.com/Akylas/com.akylas.documentscanner/assets/49267339/eee924a4-c154-4fb0-988c-3fd4e0592f9b)

![Screenshot of the theme switcher menu with light theme](https://github.com/Akylas/com.akylas.documentscanner/assets/49267339/ae193415-997c-444b-926b-288b41909708)

**Comment by farfromrefug** [comment]
@magmaus3 thanks for reporting this. i will take a look

**Comment by farfromrefug** [comment]
@magmaus3 new build should be available tomorrow
let me know if it fixes your issues
