### ISSUE TITLE
App crash during English text download

### ISSUE THREAD

**Issue by code3AGL3** [Akylas/com.akylas.documentscanner#51]
Whin I click on the text recognition button it pops to select language and language and quality l, here I click start. It automatically trys to download English language but the app crashes.

**Comment by farfromrefug** [comment]
@code3AGL3 i published a new test release. Can you try with it? https://github.com/Akylas/com.akylas.documentscanner/releases/tag/test_android
thanks

**Comment by code3AGL3** [comment]
> @code3AGL3 i published a new test release. Can you try with it? https://github.com/Akylas/com.akylas.documentscanner/releases/tag/test_android
> thanks

I tried your test version and it also crashes.

**Comment by farfromrefug** [comment]
did you restart the app after the crash? it should send me a bug report and I did not get it yet

**Comment by farfromrefug** [comment]
@code3AGL3 could you please try to reproduce the issue today? my sentry server is up and hopefully i will receive a bug report

**Comment by code3AGL3** [comment]
> @code3AGL3 could you please try to reproduce the issue today? my sentry server is up and hopefully i will receive a bug report

Wait I'll uninstall and reinstall the app and do thie process again.

**Comment by code3AGL3** [comment]
After reinstall the app downloads the language and even detects text but when i export PDF there is this issue with red text which is not in the original document![IMG_20231229_170309.jpg](https://github.com/Akylas/com.akylas.documentscanner/assets/103199561/7570fafe-2d56-42a6-b481-ec96a6119175)

**Comment by farfromrefug** [comment]
@code3AGL3 about your initial error. I know what was happening it was a mix of things:
* you had a `SocketTimeoutException` which was something related to your network.
* the app was trying to show you an error dialog to let you know but there was a bug in my code there which made it crash (fixed)


Now about the red text you see that in the test apk i send you. It is there for debugging purpose. In normal production build the text will be there (so you can search) but will be transparent

**Comment by code3AGL3** [comment]
Will the SocketTimeoutExtension be any problem in future builds.

And thanks for clarifying those errors and for developing this app.

One more thing I'll try to try to report any bug i find here for future issues.

**Comment by farfromrefug** [comment]
@code3AGL3 the thing is the `SocketTimeoutExtension` is not related to the app but to your phone trying to communicate with Github. Dont think i can do anything about it
