### ISSUE TITLE
[Bug] PDF export 

### ISSUE THREAD

**Issue by teemue** [Akylas/com.akylas.documentscanner#66]
When exporting landscape-oriented scans, some of the images are clipped / positioned partially out of the page.

Does PDF pages have to be fixed size (A4 I presume) - I would prefer them exported just as they are.

**Comment by farfromrefug** [comment]
@teemue it is a bug i will look at it. 
If you select "full" in page size, each PDF page will be the size of the image. Which i think is what you want. 
Will fix the bug as soon as possible

**Comment by teemue** [comment]
> @teemue it is a bug i will look at it. 
> If you select "full" in page size, each PDF page will be the size of the image. Which i think is what you want. 
> Will fix the bug as soon as possible

Thanks.

Where do i select the page size?

**Comment by farfromrefug** [comment]
@teemue dont export right away, choose preview. Then click on the chevron it will show options.
Options you change are saved for next exports
